ğŸ lambda:
  - service/lambda/**
ğŸ§© service:
  - any: ['service/**/*']
    all: ['!service/lambda/**']

ğŸš§ infra:
  - infra/**
  - '**/template.yaml'
  - '**/template.yml'
ğŸ”† buildkite:
  - '**/.buildkite/**'

ğŸš€ lib:
  - lib/**
  
ğŸš€ web-app:
  - web/app/**
ğŸ¦‹ web-webchat:
  - web/webchat/**
ğŸ€ web-widget:
  - web/widget/**
ğŸ mobile:
  - mobile/**
  - mobile_v2/**

ğŸ’¦ app-server:
  - service/app-server/**

ğŸ“ˆ analytics:
  - service/analytics/**
ğŸ¤– api-gateway-session-auth:
  - service/lambda/api-gateway-session-auth/**
ğŸ”’ auth:
  - service/auth/**
ğŸ’° billing:
  - service/billing/**
  - service/lambda/billing/**'
ğŸ’¬ chat-activity:
  - service/chat-activity/**
  - service/lambda/chat-activity/**
â° cloudwatch-metric-generator:
  - service/lambda/cloudwatch-metric-generator/**
ğŸªª contact:
  - service/contact/**
  - service/lambda/contact/**
ğŸ¦ contact-auto-assignment:
  - service/lambda/contact-auto-assignment/**
ğŸ¸ contact-interaction:
  - service/lambda/contact-interaction/**
ğŸ¦€ conversation:
  - service/conversation/**
  - service/lambda/conversation/**
ğŸ—ƒ data-export:
  - service/data-export/**
  - service/lambda/data-export/**
ğŸŒ¶ developer-api:
  - service/developer-api/**
  - service/lambda/developer-api/**
ğŸ–¼ image-handler:
  - service/lambda/image-handler/**
ğŸ™ integration:
  - service/integration/**
  - service/lambda/integration/**
ğŸ„ integration-pusher:
  - service/integration-pusher/**
ğŸ¥• notification:
  - service/lambda/notification/**
ğŸ— rds-to-elasticsearch-contacts-streamer:
  - service/lambda/rds-to-elasticsearch-contacts-streamer/**
ğŸ” report-segment:
  - service/lambda/report-segment/**
ğŸ• laravel-echo:
  - service/laravel-echo/**
ğŸ“£ messaging:
  - service/messaging/**
ğŸ‘¼ save-picture:
  - service/lambda/save-picture/**
ğŸŸ script-generator:
  - service/lambda/script-generator/**
ğŸ’Œ sendgrid-email:
  - service/lambda/sendgrid-email/**
ğŸ‘Ÿ service-worker-server:
  - service/lambda/service-worker-server/**
ğŸ“ slack-delivery-pipeline:
  - service/lambda/slack-delivery-pipeline/**
ğŸ› s3-virus-scanner:
  - service/s3-virus-scanner/**
ğŸ’ task-scheduler:
  - service/lambda/task-scheduler/**
ğŸ›¹ whatsapp-business-account:
  - service/lambda/whatsapp-business-account/**
ğŸ¬ webchat:
  - service/webchat/**
ğŸ™ workflows:
  - service/workflows/**
  - service/lambda/workflows/**
ğŸš‘ workflows-alarm:
  - service/lambda/workflows-alarm/**
